git: github
settings:
#  cosmos_name:
#   realm_name:
#   foundation_name:
#   application_name:
environments:
#  dev:
#    match_branch: refs/heads/main
#    stages:
#    - deploy
#    - local-test
#  sit:
#    match_branch: refs/tags/.*
#  prd:
#    match_branch: refs/tags/.*
#    match_event: release
